version: "3.9"
services:
  web:
    build: .
    depends_on:
      - "mongodb"
    ports:
      - "8080:8080"
    env_file:
      - .env
    links:
      - mongodb
  db:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'